// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plywtsazinaeehkfqlro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBseXd0c2F6aW5hZWVoa2ZxbHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTE4ODcsImV4cCI6MjA1ODg4Nzg4N30.rmIKHnLlUkyGE1BykAZ3bgAFncdUsGu7IOyWjhDBdVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);